[package]
name = "venus-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"

[dependencies]
anyhow = "1.0.95"
log = "0.4.22"
thiserror = "2.0.9"
toml = "0.8.19"
serde = { version = "1.0.216", features = ["derive", "serde_derive"] }
serde_json = { version = "1.0.134" }
json_comments = "0.2.2"
tonic = "0.12.3"
prost = "0.13.4"
reqwest = "0.12.12"
base64 = "0.22.1"
md5 = "0.7.0"
async-trait = "0.1.83"

[build-dependencies]
tonic-build = "0.12.3"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.14.0"
