name: Rust

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]
  workflow_call:
    inputs:
      rust-version:
        type: string
        required: false
        default: nightly

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/            
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Set up deno cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ./node_modules
        key: ${{ runner.os }}-deno-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-deno-
    - name: Set up dependencies
      run: make deps
    - name: Build
      run: make release
    - name: Run tests
      run: make test
